version: '3'
services:
    redis-master:
        build: ./redis/master
        container_name: ril-redis-master
        volumes:
        - $PWD/redis/master/data:/data
        ports:
        - 16379:6379
    redis-slave-01:
        build: ./redis/slave
        container_name: ril-redis-slave-01
        volumes:
        - $PWD/redis/slave/data:/data
        ports:
        - 26379:6379


    tomcat-001:
        build: ./tomcat/
        container_name: ril-tomcat-001
#        ports:
#        - 18080:8080
#        - 18443:18443
        volumes:
        - ./webapps:/usr/local/tomcat/webapps
        - ./logs/tomcat-001:/usr/local/tomcat/logs
        - ./logs/tomcat-001:/logs
        depends_on:
        - redis-master

    tomcat-002:
        build: ./tomcat/
        container_name: ril-tomcat-002
        volumes:
        - ./webapps:/usr/local/tomcat/webapps
        - ./logs/tomcat-002:/usr/local/tomcat/logs
        - ./logs/tomcat-002:/logs
        depends_on:
        - redis-master

    tomcat-003:
        build: ./tomcat/
        container_name: ril-tomcat-003
        volumes:
        - ./webapps:/usr/local/tomcat/webapps
        - ./logs/tomcat-003:/usr/local/tomcat/logs
        - ./logs/tomcat-003:/logs
        depends_on:
        - redis-master



    nginx:
        build: ./nginx/
        container_name: ril-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./webapps:/opt/webapps"
            - "./logs/nginx:/var/log/nginx"
        depends_on:
            - "tomcat-001"
            - "tomcat-002"
            - "tomcat-003"
