spring:
    jpa:
        show-sql: true  #显示 sql 语句
        database: MYSQL
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:  ## spring boot 中所有的原来配置在 hibernate.cfg.xml 中的内容都配置在 spring.jpa.properties.hibernate 下
            hibernate:
                show_sql: false
                dialect: org.hibernate.dialect.MySQL5Dialect
                ddl-auto: update
                format_sql: false #显示格式化后的 sql 语句
                use_sql_comments: true #显示注解
    redis:
        host: 120.76.101.180
        password: 1qaz369*
        port:   16379
        database:   2
    http:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1

    datasource:
        url: jdbc:mysql://120.76.101.180:3306/ril?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: ril
        password: rilril
        driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
        cache:  false
        mode: HTML

    devtools:
        restart:
            exclude: static/**,public/**

server:
    contextPath: /

context:
    listener:
        classes: pers.roamer.boracay.application.StartedListener

logging:
    config: classpath:log4j2-prod.yaml
    level:
        org:
            hibernate:
                type: info # trace 显示 sql 的参数值
